name: Auto Commit

on:
  schedule:
    - cron: "50 11 * * *"   # 17:20 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "vinupeeks"
          git config --global user.email "vinupeeks@gmail.com"

      - name: Make 10 commits
        run: |
          for i in {1..7}
          do
            node scripts/update.js
            git add .
            git commit -m "Auto commit $i $(date)" || echo "No changes"
          done

      - name: Push changes
        run: git push
